CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    display_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS topics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level TEXT NOT NULL CHECK (level IN ('A1', 'A2')),
    UNIQUE (name, level)
);

CREATE TABLE IF NOT EXISTS words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    german TEXT NOT NULL,
    english TEXT NOT NULL,
    article TEXT,
    pronunciation TEXT NOT NULL,
    plural TEXT,
    level TEXT NOT NULL CHECK (level IN ('A1', 'A2')),
    topic_id INTEGER REFERENCES topics(id) ON DELETE CASCADE,
    topic TEXT NOT NULL,
    example_de TEXT NOT NULL,
    example_en TEXT NOT NULL,
    UNIQUE (german, level, topic)
);

CREATE TABLE IF NOT EXISTS vocabulary (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    german TEXT NOT NULL,
    english TEXT NOT NULL,
    article TEXT,
    pronunciation TEXT NOT NULL,
    plural TEXT,
    level TEXT NOT NULL CHECK (level IN ('A1', 'A2')),
    topic TEXT NOT NULL,
    example_de TEXT NOT NULL,
    example_en TEXT NOT NULL,
    UNIQUE (german, level, topic)
);

CREATE TABLE IF NOT EXISTS quiz_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    level TEXT,
    topic TEXT,
    total_questions INTEGER NOT NULL DEFAULT 0,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    word_id INTEGER REFERENCES words(id) ON DELETE CASCADE,
    quiz_result_id INTEGER REFERENCES quiz_results(id) ON DELETE CASCADE,
    correct BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review_words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    word_id INTEGER REFERENCES words(id) ON DELETE CASCADE,
    wrong_count INTEGER NOT NULL DEFAULT 0,
    last_wrong TIMESTAMPTZ,
    mastered BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (user_id, word_id)
);

CREATE TABLE IF NOT EXISTS progress (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    level TEXT NOT NULL,
    topic TEXT,
    words_practiced INTEGER NOT NULL DEFAULT 0,
    words_mastered INTEGER NOT NULL DEFAULT 0,
    questions_answered INTEGER NOT NULL DEFAULT 0,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    listening_seconds INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, level, topic)
);

CREATE TABLE IF NOT EXISTS exam_attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    exam_level TEXT NOT NULL,
    exam_number INTEGER NOT NULL,
    total_questions INTEGER NOT NULL DEFAULT 50,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exam_answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_attempt_id INTEGER REFERENCES exam_attempts(id) ON DELETE CASCADE,
    word_id INTEGER REFERENCES words(id) ON DELETE SET NULL,
    correct BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS listening_questions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level TEXT NOT NULL CHECK (level IN ('A1', 'A2')),
    topic TEXT NOT NULL,
    german TEXT NOT NULL,
    english TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option TEXT NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D')),
    UNIQUE (level, german)
);

CREATE TABLE IF NOT EXISTS listening_answers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    question_id INTEGER REFERENCES listening_questions(id) ON DELETE CASCADE,
    correct BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attempts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vocab_id INTEGER REFERENCES vocabulary(id) ON DELETE CASCADE,
    correct BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_words_level_topic ON words(level, topic);
CREATE INDEX IF NOT EXISTS idx_vocabulary_level_topic ON vocabulary(level, topic);
CREATE INDEX IF NOT EXISTS idx_attempts_vocab ON attempts(vocab_id);
CREATE INDEX IF NOT EXISTS idx_listening_answers_question ON listening_answers(question_id);
